### ISSUE TITLE
World hangs when `difficulty_modifier` object is used on properties files

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Insane-96/MobRandomness#100]
**Versions**:
* Minecraft:  1.18.2
* Forge: 40.1.52
* Mobs Properties Randomness: 3.3.4
* InsaneLib: 1.5.1

**What Happens**:  
I have noticed that when I have quite a few mob properties files loaded that the game just freezes after a varying amount of time and I have to then use task manager to forcibly close the game. The main indication of this is chunks just stop loading, like this:
![2022-06-26_09 40 47](https://user-images.githubusercontent.com/64381954/175807060-2d7f14e1-7c0d-40de-8fe1-54d3144ea8c3.png)
Mobs will also just freeze and not be able to be interacted with.

I had just added a world difficulty modifer to all the chance values in the properties files before this started occurring so I'm not sure if the game is just trying to do too much and just stopping? If I delete all or most of the mob properties files then this issue disappears so this might be the case.

It might be worth checking if I've done the chance modifiers correctly as I've only just implemented them so I'm not sure if I might have done something wrong with them.

**Logs / Crash reports**:  
Latest Log: https://gist.github.com/NJL5390/8da0dd3c3d569f49f23b5830332a5ff6
Mob Properties Log: https://gist.github.com/NJL5390/ae530525781e0923086d6c8d33c3744c

**Config Folder**:  
[MobsPropertiesRandomness.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/8987195/MobsPropertiesRandomness.zip)

**Can be reproduced with Mobs Properties Randomness only? (InsaneLib is mandatory in 1.16+)**:  
EDIT: YES, It can, I have since swapped out the armors from  immersive armors with vanilla armours in the mob properties files and I was still able to reproduce this issue, so this definitely seems to be an issue with mob properties.

Thanks for the great mod! It has been incredibly useful for my modpack that I make and play with my friends!

**Comment by The-Bernician-Lamb** [comment]
Just want to provide an update to this issue. Based on my testing this CAN be reproduced with only InsaneLib and Mob properties  Randomness. When I used the above Properties files and swapped out the modded items for vanilla items, I was still able to reproduce this issue.

So this issue isn't happening in relation to another mod, therefore it is either a result of a bug with mob properties / insane lib or a result of my awful ability to write JSON files.

(Also I've found that I can more reliably reproduce this issue if I try and locate structures in the nether, if that's any help at all.)

EDIT: Here's the debug log from my latest testing session in case you need it: https://gist.github.com/NJL5390/2314d721f9023bdf935a6bd26fda8f09

Please let me know if you need any more information or testing from me and I'll be happy to help!

**Comment by The-Bernician-Lamb** [comment]
Ok, So after extensive testing and modifying of my properties files, I think I've made a breakthrough in relation to this issue. This issue appears to be caused by the difficulty modifiers that I had used in the properties files.

UPDATE: Seems to happen specifically when "difficulty_modifier" is used, I haven't had problems when using "local_difficulty" modifer in the past.

**Comment by The-Bernician-Lamb** [comment]
Alright, So my testing that I have done has confirmed my suspicions, It seems to be the "difficulty_modifier" object that was causing the problem the entire time. So putting the object like this works fine and causes no issues:

                 "world_difficulty": {
                  "operation": "add",
                  "easy": -0.05,
                  "hard": 0.05
                            }

However, if formatted like below, then it causes the game to freeze after a varying amount of time:

                "difficulty_modifier": {
                 "world_difficulty": {
                  "operation": "add",
                  "easy": -0.05,
                  "hard": 0.05
                            }
                         }

This seems to be the cause of the entire issue, as after I changed my difficulty modifiers to be like the first example, the issue stopped occurring altogether and everything worked fine.

I'll leave this issue with you now to either see if this can be addressed or update the wiki to warn about this issue. But feel free to let me know if you want me to do any more testing or give any more information in relation to this issue.

Cheers.

**Comment by Insane96** [comment]
The first one does nothing that's why no longer freezes the game.

**Comment by Insane96** [comment]
~~Also could you send the new jsons with MPR only that causes issues?~~

NVM I see the zip you provided already has only vanilla armor

**Comment by Insane96** [comment]
So, finally found out that `local_difficulty` hanged the world because rarely the mob would spawn before the chunk is generated, causing a deadlock. Next update I'm going to remove the feature as
![image](https://user-images.githubusercontent.com/7185104/176136332-08ad1640-5873-49f1-a0eb-176ce67ee81e.png)

EDIT: Seems like using the difficulty_modifier object also causes the problem (as the local difficulty is checked even if there's no modifier). So the world will still hang even after removing the `local_difficulty` modifier.

If you want to prevent the freeze just remove all the `local_difficulty` instances in the jsons and you're set.  
Also loving how you're using the mod.

**Comment by The-Bernician-Lamb** [comment]
> So, finally found out that `local_difficulty` hanged the world because rarely the mob would spawn before the chunk is generated, causing a deadlock. Next update I'm going to remove the feature as ![image](https://user-images.githubusercontent.com/7185104/176136332-08ad1640-5873-49f1-a0eb-176ce67ee81e.png)

Fair enough, I only found out what local difficulty was by looking at the Minecraft Wiki. Plus I only found out it existed by looking at the debug screen.
> EDIT: Seems like using the difficulty_modifier object also causes the problem (as the local difficulty is checked even if there's no modifier). So the world will still hang even after removing the `local_difficulty` modifier. If you want to prevent the freeze just remove all the `local_difficulty` instances in the jsons and you're set. 

I see, thanks for letting me know. I will adjust my properties files accordingly. 
>Also loving how you're using the mod.

Thanks! I spent quite a while on it and was heavily inspired by Minecraft Dungeons and their armored and biome variants of mobs. (https://www.minecraft.net/en-us/about-dungeons). Plus just how the armours from Immersive armors looked gave me some inspiration too! (https://www.curseforge.com/minecraft/mc-mods/immersive-armors)

**Comment by Insane96** [comment]
Fixed in 3.3.5
