### ISSUE TITLE
1.16.5 json files not working

### ISSUE THREAD

**Issue by TheEffortFighter** [Insane-96/MobRandomness#102]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.16.5
* Forge: 36.2.34
* Mobs Properties Randomness: MobsPropertiesRandomness-3.3.0-mc1.16.5.jar
* InsaneLib: InsaneLib-1.4.2-mc1.16.5.jar

**What Happens**:  
My JSON files don't load in ingame, I'm trying to modify my game so skeletons have a 50% (it's 100% in the example because I was trying to make sure it worked, but it still didn't) chance to spawn in with no weapon or a small chance to spawn in with a diamond one, I did /reload whenever I edited the JSON file and put the mobs JSON files in the mobs folder in the configs for this mod.

//Please send Minecraft logs and MobsPropertiesRandomness.log  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  https://gist.github.com/TheEffortFighter/a07ec585cc93348937965d283e1fb357
E.g. https://pastebin.com/1AbCDEFG

//Send the mod's config folder with all the jsons and groups
**Config Folder**:  https://www.mediafire.com/file/a5ikoacdcbfo7eq/MobsPropertiesRandomness.zip/file
E.g. MobsPropertiesRandomness.zip

**Can be reproduced with Mobs Properties Randomness only? (InsaneLib is mandatory in 1.16+)**:  
Yes

**Comment by Insane96** [comment]
It's value and not amount
