### ISSUE TITLE
My datapack isn't working

### ISSUE THREAD

**Issue by woodgoldtwo** [Insane-96/MobRandomness#107]
I've followed the wiki and made a datapack but it doesn't work, the MobsPropertiesRandomness.log just says that 0 .json files are loaded

Here is the .json in question:

{
    "mob_id": "minecraft:skeleton",
    "equipment": {
        "main_hand": {
            "chance": 0.25,
            "items": [
                {
                    "id": "minecraft:stone_sword",
                    "weight": 10
                }
            ]
        },
        "off_hand": {
            "chance": 0.25,
            "items": [
                {
                    "id": "minecraft:shield",
                    "weight": 10
                }
            ]
        }
    }
}

**Comment by Insane96** [comment]
You gave 0 useful infos and you didn't follow the Bug Report template. Reopen with that.
