### ISSUE TITLE
[Suggestion] Compat with Enhanced AI

### ISSUE THREAD

**Issue by CTH999** [Insane-96/MobRandomness#109]
Basically, my idea is "simple". If you have [Advanced AI](https://www.curseforge.com/minecraft/mc-mods/enhanced-ai), you can manipulate:

1. Which AI effects a mob gets (A mini-boss creeper with all the effects?)
2. Use the other mod to access this one. Maybe the probability of an effect from this one can be set to change based on AI. You want skeletons labled as "spammers" to have higher health, and be faster? Sure... have fun! Or, use this to make it so that _if_ a Spammer, it's guarenteed to have straffing!

Just some thoughts!

**Comment by Insane96** [comment]
You can already do that: https://github.com/Insane96/EnhancedAI/wiki/Entity-Tags

**Comment by CTH999** [comment]
okay
