### ISSUE TITLE
Not reading or even recognizing json file

### ISSUE THREAD

**Issue by jlaine3333** [Insane-96/MobRandomness#110]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.18.2
* Forge: 40.2.0
* Mobs Properties Randomness:  4.0.1
* InsaneLib: 1.5.3

**What Happens**:  
The .json files in the datapack (within the /mobs_properties_randomness/mobs folder) don't load.
 
**Logs / Crash reports**:  
[INFO] Loaded 0 Presets 
[INFO] Loaded 0 Mob(s) 

//Send the Datapack that's not working
**Datapack**:  
[silverfishnerf.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/11515319/silverfishnerf.zip)

**Can be reproduced with Mobs Properties Randomness only?**:  
Yes

**Comment by Insane96** [comment]
This is not how you make a datapack.
https://minecraft.fandom.com/wiki/Data_pack#Folder_structure
The mobs_properties_randomness folder is like the advancements or recipes folder
