### ISSUE TITLE
My code doesnt works and I'm not not sure why?

### ISSUE THREAD

**Issue by matzar24** [Insane-96/MobRandomness#111]
**Versions**: 4.2.0
* Minecraft:  1.19.2
* Forge: recomended
* Mobs Properties Randomness: yes
* InsaneLib: sure

**What Happens**:  Nothing in particular...
Properties which I added - I don't see zombies & skeletons wearing them :(
Potion effects, armours, weapons to zombies & skeletons.
I was looking a lot and chance is 10%, 
So I'm guessing my very top of code is wrongly tagged with target or mob_id.

I don't get any errors or logs.

[MTmobs - Copy.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/11729123/MTmobs.-.Copy.zip)
This folder is in my world save datapack folder.

**Comment by Insane96** [comment]
File and folder names (except the data pack folder) must be lowercase

**Comment by Insane96** [comment]
Also read the wiki: https://github.com/Insane96/MobsPropertiesRandomness/wiki/%5BVersion-4.1%5D-Mobs
Your json is quite wrong.

Also also, don't know what you're using, but I recommend VSCode to edit JSON, as it checks for syntax

**Comment by matzar24** [comment]
Syntax is not a problem, I checked in VS and everything is right.
Also corrected datapack version to 9, so it would work on 1.19.
I lowercased file & folder names.
Also checked for discrepancies and everything looks like in structure examples shown in wiki.
One small change I'm done I changed target's & mob_id's brackets for [ ], instead of previously { }.
Still I dont see zombies wearing my equipment. IDK what is wrong.

**Comment by Insane96** [comment]
Any error? Also READ the wiki, don't just check examples. Examples might be wrong. Also the syntax was wrong, and the file is still not valid if you changes what you mentioned.

**Comment by matzar24** [comment]
I mean, I corrected everything I could, but this still doesnt work.
Also changed again version from 9 to 10, bc other wiki says 1.19 is version 10.
Even added "chance": 1.0  for levitation, so it would be easier spot affected mob.

I'm uploading corrected version.
[mtmobs.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/11737251/mtmobs.zip)

**Comment by matzar24** [comment]
Correction: Albeit I getting logs, I have newest logs on top and on bottom...
But it says only:
[INFO] Loaded 0 Presets 
[INFO] Loaded 0 Mob(s) 
00:27 I found sth interesting, I'll give sign if everything is right

**Comment by matzar24** [comment]
Everything works fine after finally I found proper log file with java error notions.
Missing bunch of , : [ {
It's pain to write in NOtepad :(
Especially when VScode tells you everything is fine, no, it's not fine...
Photo for proof
![2023-06-14_00 55 31](https://github.com/Insane96/MobsPropertiesRandomness/assets/47837757/e45d2562-1072-4b53-be2c-247d90320f90)
