### ISSUE TITLE
Shouldnt it give 100% chance on the bedrock level?

### ISSUE THREAD

**Issue by matzar24** [Insane-96/MobRandomness#112]
**Versions**: 4.1.1
* Minecraft:  1.19.2
* Forge: recomended
* Mobs Properties Randomness: yes
* InsaneLib: sure

**What Happens**:  
I wanted so every zombie deeper you go the better equipment they have.
From my calculations if basic chance is 0.1 and it's starting at 64, 
then 100% will be achieved by increasing this value by 0.007 each block deeper. 
0.1 + 128*0.007 = 0.1 + 0.896 = 0.996 ~= 100%
But they don't give a shit and their equipment spawn only with 0.1 chance...

[zombie - Copy.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/11747867/zombie.-.Copy.txt)

**Comment by Insane96** [comment]
Enable the debug flag in the config and check if the pos modifier is actually loading in the log

**Comment by matzar24** [comment]
I enabled this option and nothing is happening in log file.

[DEBUG] Initialized! 
[INFO] Loaded 0 Presets 
[INFO] Loaded 5 Mob(s)

**Comment by matzar24** [comment]
Found out what's going on.
Modifier is changing value by percent of percent value. Very unintuitive.
So instead simply 0.1 + 128 * 0.007, it requires 0.1 + 128 * 0.1 * 0.07 ~= 100%
But if chance is more custom like 0.3, then it's getting more & more complicated: 0.3 + 128 * 0.3 * 0.018 ~= 100%
From math perspective it's very logical, but from practical perspective I would advise to simplify this to more intuitive version.

**Comment by Insane96** [comment]
So it works like it's stated in the wiki https://github.com/Insane96/MobsPropertiesRandomness/wiki/%5BVersion-4.0%5D-Position-Modifier. There's a wiki with most of the infos for a reason.
Closing.

**Comment by Insane96** [comment]
Will think about a way to simplify that

**Comment by matzar24** [comment]
Thanks, I just didnt get earlier the idea for searching outdated mod's wiki version.

**Comment by Insane96** [comment]
This has been addressed in 4.5.2, where you can use `"operation": "add"` to give a flat increase to the value.
