### ISSUE TITLE
the client crashed while using WorldWhiteList

### ISSUE THREAD

**Issue by Ngnlant** [Insane-96/MobRandomness#120]
**Versions**:
* Minecraft:  1.19.2
* Forge: 43.2.14
* Mobs Properties Randomness: 4.2.0.1
* InsaneLib: 1.7.5

**What Happens**:  
the client crashed while using WorldWhiteList

This is the reason:
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.isEmpty()" because "this.biomes" is null
	at insane96mcp.mobspropertiesrandomness.data.json.util.MPRWorldWhitelist.doesBiomeMatch(MPRWorldWhitelist.java:62)

And this is the part that went wrong:
"world":{
    "dimensions":[
        "minecraft:overworld"
    ]
}

there is no "biomes" part,so the variable "biomes" is null(not an arraylist),so the method "isEmpty" cannot be called.
it's the reason why the crash happened.

and after i added  ' "biomes":[] ' into the object,it worked correctly.
like this:
"world":{
    "dimensions":[
        "minecraft:overworld"
    ],
    "biomes":[]
}

pls judge if "biomes" is null before calling "isEmpty" or initialize it  with an empty arraylist.

**Comment by Ngnlant** [comment]
i guess other variables have the same problem.
It'd be great if you'd check them out.

**Comment by Insane96** [comment]
Fixed in 1.19.2 and 1.19.4
1.20.1 will be fixed later
