### ISSUE TITLE
I suspect the world whitelist is not working.

### ISSUE THREAD

**Issue by J-Kikutaro** [Insane-96/MobRandomness#124]
This is using machine translation
I wrote the following Json to spawn Enderman with 1.5x HP only in End Dimension, but the result is that Enderman spawns with 1.5x strength even in overworld!
I used this wiki ( https://github.com/Insane96/MobsPropertiesRandomness/wiki/%5B1.16+%5D-Attributes ) as a reference, but I don't know if I'm doing something wrong or if it's a glitch in the mod! .
How can I make it behave the way I expect it to?

Mod ver
MobsPropertiesRandomness-3.3.0-mc1.16.5.jar
InsaneLib-1.4.2-mc1.16.5.jar

Json File
[end_ender.json](https://github.com/Insane96/MobsPropertiesRandomness/files/13628726/end_ender.json)

MPR.log
[MobsPropertiesRandomness.log](https://github.com/Insane96/MobsPropertiesRandomness/files/13628729/MobsPropertiesRandomness.log)

Screen shot(No Json)
![2023-12-11_02 36 58](https://github.com/Insane96/MobsPropertiesRandomness/assets/142008350/db55dfbe-032c-4145-b15a-c532d89e2834)

Screen shot(Json)
![2023-12-11_02 33 50](https://github.com/Insane96/MobsPropertiesRandomness/assets/142008350/7eb3baa6-962d-47fb-bc6e-dd638618bc4d)

**Comment by Insane96** [comment]
Sorry 1.16 is no longer supported

**Comment by 2929762171** [comment]
Try [InControl](https://www.curseforge.com/minecraft/mc-mods/in-control)
