### ISSUE TITLE
Refuses to load mobs even after following the wiki. What am I doing wrong?

### ISSUE THREAD

**Issue by Lerrycapetime** [Insane-96/MobRandomness#125]
Tried finding a video guide to see if I was placing it in the wrong folder, it says to place it in the data folder, but shouldn't it go in datapack in the saves folder? I tried both and nothing worked.

.Minecraft\saves\Test\datapacks\MobRandomnessDataPack\mobs_properties_randomness\mobs
.Minecraft\saves\Test\data\MobRandomnessDataPack\mobs_properties_randomness\mobs
Minecraft Launcher\.Minecraft\data\MobRandomnessDataPack\mobs_properties_randomness\mobs

Also just did a test by copying and pasting the code from the wiki and still won't load up, I have it all lowercased for folders. Some help would be greatly appreciated.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.17
* Mobs Properties Randomness: 4.9.0-mc1.20.1
* InsaneLib: 1.12.1-mc1.20.1

**What Happens**:  
Explain what's the problem
Simply won't load up.

**Comment by Insane96** [comment]
The first one is correct

**Comment by Insane96** [comment]
Also this isn't enough infos. Make sure the datapack is valid

**Comment by Lerrycapetime** [comment]
[MobRandomnessDataPack.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/13648532/MobRandomnessDataPack.zip)
I made a few test examples in here, packed it into a zip, I've tried both extracted and zip versions just to be sure, also these are inside the save folder datapack as correct, most notably the ghost zombie and zombie from the wiki. As confirmation, does it look correct? Wouldn't this be labeled as a valid datapack? Am I missing an important step? Could a different Drive Letter interfere? I have MC loaded on a second harddrive. If I'm doing something wrong, could you provide a zip to a correct way of doing it? Thank you.

**Comment by Insane96** [comment]
This is wrong. in the zip the pack.mcmeta must be on top most level. and you're also missing the namespace

**Comment by Lerrycapetime** [comment]
This doesn't help, clearly you don't understand nor could provide an example, just going with a different mod, thanks.

**Comment by Insane96** [comment]
You don't understand. There are examples datapack on the discord server and it's clearly stated both in the mods' wiki the folder structure and minecraft wiki how data packs work.
