### ISSUE TITLE
Additional custom sound by resourcepacks is invalid for play_sound events

### ISSUE THREAD

**Issue by betterworld-sjq** [Insane-96/MobRandomness#128]
1.20.1 forge
The custom sound added additionally (yep not overriding vanilla, but add new sound) can play well with command /playsound in the chatting bar. But when I applied the sound to play_sound events in MPR in a mob's preset, it just ruined the whole file, making the preset not working at all.
And I'm pretty sure no other format mistake in the preset file because it worked normally when I substitute the sound with vanilla sound.

**Comment by Insane96** [comment]
[Replicants_Soundpack.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/13785343/Replicants_Soundpack.zip)
The resource pack used
