### ISSUE TITLE
Forgotten Configuration [Off-Hand/Knockback Resistance]

### ISSUE THREAD

**Issue by Liryax** [Insane-96/MobRandomness#13]
I've noticed that random Knockback Resistance is missing from the config file, as well as Off-Hand Item from the 1.3.0 version.

**Comment by Insane-96** [comment]
It works for me

**Comment by Liryax** [comment]
Well, It doesn't for me, using the last version published on CurseForge, checking twice that I didn't kept the older version instead, deleting the config file to make sure it regenerate, I still get this https://pastebin.com/yFiL0qRn which I'm definitive, doesn't contain the Off-Hand and Knockback Resistance feature.

Though  in fact, the problem isn't there. I've used a Java Decompiler program to check if it match with the code I see on GitHub, and well... It don't.

`//RNGEntity.class
if (mobEquipments.isEmpty())
    {
      LoadEquipment(equipment, EntityEquipmentSlot.HEAD);
      LoadEquipment(equipment, EntityEquipmentSlot.CHEST);
      LoadEquipment(equipment, EntityEquipmentSlot.LEGS);
      LoadEquipment(equipment, EntityEquipmentSlot.FEET);
      LoadEquipment(equipment, EntityEquipmentSlot.MAINHAND);
     // Here is missing : LoadEquipment(equipment, EntityEquipmentSlot.OFFHAND);
    }`

So I think that you might have compiled and published the wrong version of the mod on CurseForge.

**Comment by Insane-96** [comment]
Happens on 1.12?

**Comment by Insane-96** [comment]
Reuploaded correct 1.12 version: https://minecraft.curseforge.com/projects/mobs-properties-randomness/files/2529303
