### ISSUE TITLE
Spawner Behavior Malfunctioning

### ISSUE THREAD

**Issue by BodhiSmith13** [Insane-96/MobRandomness#130]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.0
* Mobs Properties Randomness: 4.10
* InsaneLib: 1.12.1

**What Happens**:  
Spawner Behavior does not prevent presets from being applied. So if I set a preset to apply only to mobs being spawned from spawners, it is instead applied to all mobs. 

//Please send Minecraft logs and MobsPropertiesRandomness.log  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://gist.github.com/BodhiSmith13/2bc4def5fc42c09bde14ee340509a842
https://gist.github.com/BodhiSmith13/f0c095dcc8c28fd04d199141feaed95d

//Send the mod's config folder with all the jsons and groups
**Config Folder**:  
[mobs_properties_randomness.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/13969140/mobs_properties_randomness.zip)

**Can be reproduced with Mobs Properties Randomness only? (InsaneLib is mandatory in 1.16+)**:  
Yes

**Comment by Insane96** [comment]
It's `spawner_behaviour` not `spawner_behavior`

**Comment by BodhiSmith13** [comment]
Yup that was the problem. Thank you, and please excuse me while I go back to kindergarten to learn basic spelling.
