### ISSUE TITLE
[1.12.X] The Re-Upload is the new version of the mod, but for 1.11

### ISSUE THREAD

**Issue by Liryax** [Insane-96/MobRandomness#14]
Well it was better this time, and yes, my issues was indeed in 1.12, I'll think about indicating that from now on. Though the Re-Upload is actually for 1.11. At least it's the correct mod version :)

**Comment by Insane-96** [comment]
I can't do something right today. I'm too hyped for my Nintendo Switch getting delivered tomorrow :P
..
Reupoloaded
