### ISSUE TITLE
[1.12.X] Giving Equipement to mobs seems to work in reverse (Giving it to any OTHER mobs)

### ISSUE THREAD

**Issue by Liryax** [Insane-96/MobRandomness#15]
Sometimes I fell like it's kinda impolite to write so much issues, fell like I'm constantly whining. Well, I know this is a wrong felling though, after all writing issues is supposed to help you so there is nothing wrong with that if I do it right. ^^

Anyway, about the bug, at first, I though the monster id was simply ignored because I noticed that some unexpected mobs had Totem Of Undying while I only gave them to minecraft:zombie and minecraft:husk (And I'll add them for Skeletons and Stray soon, now that I can affect the off-hand). Though it was a minor bug, it could make it annoying to hunt animals for food as they could get a Totem Of Undying and live twice too, etc...
Well, I noticed though after adding 33 modded arrows for Skeletons only that actually any mobs got them beside the Skeletons, so I concluded that the mob id wasn't actually ignored, but used to tell who don't get the item instead of who can get it.

Before reporting the bug I tried to take a look at the code so I could save your debuging time, and, well, I didn't check the whole code but I think I might have found where there is something wrong : 

In RNGEntity.class, in the function Equipement (Line 79), in the for loop (Line 90), the condition line 92 is : 

`if (EntityList.isMatchingName(living, mobResourceLocation))
continue;`

Which seems to mean that it'll skip to the next iteration of the for loop if the name of the Spawned Mobs match the name written in the config file. So I think it's the opposite of what we want there and that the condition should pass if the names doesn't match instead.

Of course as I said, I didn't checked the whole code so I might be wrong there, but I guess it worth trying to help you with it. :)

EDIT : (And all that to be in the end disappointed because apparently, Skeletons only use their off-hand for Tipped Arrows, because of that, Modded Arrows doesn't work... Well, at least the Off-Hand is still useful for the Totem Of Undying ^^)

**Comment by Insane-96** [comment]
Not annoying at all, I love that someone cases :P
Btw I'll check it tomorrow, but as a fast lookin it might be true
