### ISSUE TITLE
Crash when loading minecraft

### ISSUE THREAD

**Issue by kellixon** [Insane-96/MobRandomness#20]
MC 1.12.2. MobsPropertiesRandomness 2.0.0.
Error - java.lang.IllegalArgumentException: Multiple entries with same key: mobspropertiesrandomness=FMLMod:mobspropertiesrandomness{2.0.0} and mobspropertiesrandomness=FMLMod:mobspropertiesrandomness{1.3.3}. To index multiple values under a key, use Multimaps.index.
Crash report - https://pastebin.com/65U0Yzcw

**Comment by Insane96** [comment]
You have both the old and the new version installed?

**Comment by kellixon** [comment]
Only MobsPropertiesRandomness 2.0.0 In the crash report can be seen in the source column MobsPropertiesRandomness 2.0.0.jar and and the next line again MobsPropertiesRandomness 2.0.0.jar

**Comment by Insane96** [comment]
Well, it's in alpha for a reason
Thanks for reporting ;)

**Comment by Insane96** [comment]
Fixed in 2.0.1 👍
