### ISSUE TITLE
can not get nbt to work

### ISSUE THREAD

**Issue by MSandro** [Insane-96/MobRandomness#34]
[1.12.x] Mobs Properties Randomness 2.0.8

I try to give Zombies the space suit from Advanced Rocketry with one high pressured tank with oxygen. But the items doesn't accept the nbt values. I've used the "ct hand" command to get the values.

**Comment by Insane96** [comment]
The wiki is misleading right now since it's getting an update for 2.1
In 2.0 you need to put the NBT in the tag 'tag'
E.g. `"nbt": "{tag:{advRocketryTagsHere}}"`
