### ISSUE TITLE
Disable Chat Message

### ISSUE THREAD

**Issue by mrdeadlocked** [Insane-96/MobRandomness#47]
Great mod! Could we have an option to disable the login chat message both client + server?

![image](https://user-images.githubusercontent.com/461352/53662121-1fbbaa00-3c30-11e9-802e-69d16272606b.png)

**Comment by Insane96** [comment]
If I didn't mess up things, those messages shouldn't show up if `Debug` is disabled

**Comment by mrdeadlocked** [comment]
Yep! We missed having to do it on both server + client! Thanks!
