### ISSUE TITLE
Re-Add 'affected_by_local_difficulty'

### ISSUE THREAD

**Issue by ghost** [Insane-96/MobRandomness#49]
I was wonder if the 'affected_by_local_difficulty' feature could be re-added? I found it to be pretty interesting, especially when accompanied by 'local_difficulty_multiplier' as well. In the past I used this feature and it would be nice to see it return in the 2.0 editions of Mob properties Randomness in the config file.

**Comment by Insane96** [comment]
This is already in for Chance and Difficulty objects

```
"affected_by_difficulty": true,
"is_local_difficulty": true
```
