### ISSUE TITLE
"multiplier" ignores values lower than 1

### ISSUE THREAD

**Issue by ghost** [Insane-96/MobRandomness#50]
- Suggestion:

When using "is_local_difficulty" and "multiplier" together, the local difficulty value accepts and uses values of 1 and higher for the "multiplier" but doesn't accept any values lower than 1, in my opinion this seems like an unnecessary restriction. It would be nice if the "multiplier" object was allowed to be any real value. (if that can't be done then at least any real, positive and non 0 value? Any potential failure to met the criteria would error with the appropriate information needed to correct it).

- Example Script:

```
{
	"mob_id": "minecraft:enderman",
	"attributes": [
			{
				"id": "generic.maxHealth",
				"modifier": {
					"min": 35,
					"max": 35
				},
				"is_flat": false,
				"affected_by_difficulty": false,
				"difficulty": {
					"affects_max_only": false,
					"is_local_difficulty": true,
					"multiplier": 0.3
				}
			}
		]
}
```

- Reason:

I tested going back and forth between 0.3 and 1 for a specific local difficulty and it gave the same health output (I specifically tested 2.3 difficulty). My goal is to calculate what the absolute min and max values are expected to be for a specific min max value as to get the final entity health over time for hard mode (2.25 up to 6.75), therefore to help me figure out what is the most ideal value to set min and max to for hard difficulty gameplay. I can't do this with 0.3 which I would like to be able to do in the future, from other calculations for the local difficulty range, the ideal ratio I want to use is 0.296, which I am just using 0.3. I also plan on making an additive merge with flat values effected by normal difficulty too etc. I'll be repeating these processes for a plethora of other vanilla and modded entities as well with multiplier ratios that are under 1.

**Comment by Insane96** [comment]
Does the log output something?

**Comment by Insane96** [comment]
Uhm this might be happening because here I use the multiplier only on the max value
`						max *= attribute.difficulty.multiplier;`

**Comment by Insane96** [comment]
I will probably rewrite this to be less confusing https://github.com/Insane96/MobsPropertiesRandomness/blob/2.0/common/insane96mcp/mpr/json/Attribute.java#L98-L135
