### ISSUE TITLE
Attributes rounded values setting

### ISSUE THREAD

**Issue by ghost** [Insane-96/MobRandomness#52]
I don't know how practical this is but it was random thought that popped into my head, the concept is a setting called "is_whole" (or any other variation that could suit it better), if set to false internal calculations would function as normal allowing decimals (is false by default), if true it would round internally calculated values to the nearest whole number before applying it to the entity(s) in reference.

The "is_whole" feature would primarily be most useful as a companion to "is_local_difficulty" (usable with easy, normal and hard multipliers too) to flatten out attribute values (especially since mods that reveal entity health can show messy decimals).

E.g. if I have a script that increases a zombies health by 5% multiplied by the local difficulty, if the difficulty is 5.34 then with the feature enabled the output would be 25 instead of 25.34.

**Comment by Insane96** [comment]
Sorry for 2 months late reply. On the TODO list!

**Comment by Insane96** [comment]
Moved to #77
