### ISSUE TITLE
Add NBT to mob properties

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Insane-96/MobRandomness#58]
From what I can tell from the wiki it doesn't look like a mob's nbt can be controlled with this mod. This would be useful for things like custom mob names and custom 'jockeys' with passenger nbt. 

Even better: these things could be added as MPR-implemented features to allow for more flexibility (like MPR does with armor, which could be controlled with NBT but it's much easier to configure with MPR's implementation). 

Another feature that would be great is to be able to give mobs on-hit effects like vanilla husks' hunger-on-hit effect. Not sure if this is reasonable to implement and in-scope though.

**Comment by Insane96** [comment]
Wow, didn't notice this issue.
So

> Another feature that would be great is to be able to give mobs on-hit effects like vanilla husks' hunger-on-hit effect. Not sure if this is reasonable to implement and in-scope though.

Definitely in scope, but don't think is easy to implement

> Even better: these things could be added as MPR-implemented features to allow for more flexibility (like MPR does with armor, which could be controlled with NBT but it's much easier to configure with MPR's implementation).

Neat idea

**Comment by Insane96** [comment]
Added `nbt` and `raw_nbt` in 3.5.0
