### ISSUE TITLE
Mobs not Spawning with full max health

### ISSUE THREAD

**Issue by Squatlock** [Insane-96/MobRandomness#63]
Hello, I am trying to use the generic.maxhealth attribute on zombies, but they are spawning with only 20 of that hp filled. Do I need to add a health tag like in a summon command, if so where does it go in the json?

**Comment by Insane96** [comment]
Could you send the JSON?

**Comment by Squatlock** [comment]
Here you go, had to change it to a .txt to attach it.
[minecraft_zombie - Copy.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/5430645/minecraft_zombie.-.Copy.txt)

**Comment by Insane96** [comment]
generic.addhealth is not an attribute

**Comment by Squatlock** [comment]
Sorry, messed that up when I re added that to send, even with it set to generic.maxhealth it still does not fill there health.

Here is the corrected that I tested.
[minecraft_zombie - Copy.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/5430751/minecraft_zombie.-.Copy.txt)
 file

**Comment by Insane96** [comment]
It's generic.maxHealth

Il Ven 23 Ott 2020, 18:44 Squatlock <notifications@github.com> ha scritto:
