### ISSUE TITLE
Mod seems to not be working on SpongeForge

### ISSUE THREAD

**Issue by SlimefrogSocial** [Insane-96/MobRandomness#64]
I am trying to open a server with a Beta testing mod called DragonFire. I am trying to make the dragons and other entities have armor and armor toughness to make them harder to kill. I set all my settings on a client version and they worked and then moved them to my server and they don't. I have reloaded the server and reloaded the config and it isn't taking affect. I feel it may be an issue with Sponge or something, could you take a look?
Log:
https://pastebin.com/aYJHmuGj
https://pastebin.com/8wZv1DmR
Config:

[MobsPropertiesRandomness.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/5543768/MobsPropertiesRandomness.zip)

**Comment by Insane96** [comment]
I have absolutely no idea, SpongeForge is known for breaking mods pretty easily. There's no error in the logs soo I really don't know.

**Comment by SlimefrogSocial** [comment]
Thank you! I will try removing SpongeForge and try upgrading SpongForge and see if either of those fix it! I will report back when that is finished.

**Comment by SlimefrogSocial** [comment]
Removing sponge fixed it, must be an issue with sponge. I will fiddle with plugins and narrow it down to sponge in general or a particular plugin, thank you!
