### ISSUE TITLE
Armor Max Cap?

### ISSUE THREAD

**Issue by SlimefrogSocial** [Insane-96/MobRandomness#65]
On the same config as my last issue, I seem to be having a completely unrelated problem. As in my last issue I got this mod to work in client but when applying the changes to the server they did not work. While on the client, I have tested and made sure I like all my settings. I have many dragons that go well above the max attribute for armor. The Bewilderbeast for example has so much armor it should be basically untouchable. But when I reload my guns, after about 3 mags the dragon is completely dead. No matter how many hundreds of armor points I give it it is not gaining any more protection then it has since I gave it some in this mod. I have a mod called Attribute Fix that fixes the attribute maxes and they are set to several thousand each. Does this mod have a max cap built in? Is there a way to override it?
Config:
[MobsPropertiesRandomness.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/5547780/MobsPropertiesRandomness.zip)

**Comment by Insane96** [comment]
There's no cap in the mod. Might it be that the weapon deals damage that ignores armor?

**Comment by SlimefrogSocial** [comment]
The weapons might have something like that, but the armor is making a small difference. When setting them at 30 and such as I did for many of them the damage went from 5.5 to about 1 to 3 damage. Although, the big dragon with the crazy amounts of armor is taking the same amount as those. I will look into AtributeFix and see if I am doing something wrong there, thank you for responding so quickly (both of these times)!
