### ISSUE TITLE
Wrong side on Network Init

### ISSUE THREAD

**Issue by sironin** [Insane-96/MobRandomness#76]
Server network init attempts to call the client world from 3.0.3 on.

Seems related to creeper fuse fix.

**Comment by Insane96** [comment]
Follow the issue template.

**Comment by sironin** [comment]
Alright man.

Good luck with that.

**Comment by Insane96** [comment]
What?

**Comment by sironin** [comment]
[crash-2021-09-19_17.03.01-fml.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/7192918/crash-2021-09-19_17.03.01-fml.txt)
[crash-2021-09-19_17.08.08-fml.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/7192922/crash-2021-09-19_17.08.08-fml.txt)
[crash-2021-09-19_17.08.45-fml.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/7192923/crash-2021-09-19_17.08.45-fml.txt)

**Comment by Insane96** [comment]
You still didn't reopen the issue and followed the issue template. Also the problem has been fixed in the latest Alpha so ... locking this
