### ISSUE TITLE
Game crashes when I start a world

### ISSUE THREAD

**Issue by Dster5** [Insane-96/MobRandomness#79]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.16.5
* Forge: 1.16.5-forge-36.2.5
* Mobs Properties Randomness: alpha 3.1.0
* InsaneLib: 1.2.1

**What Happens**:  
Explain what's the problem

when I load up the game everything is fine but when I load into a world it loads then I spawn for a few seconds and then it freezes and crashes. also it only crashes when I put text into the json file. If I play with the mods with the json file empty it doesnt  crash. Im currently using the first armor example from the wiki.

//Please send Minecraft logs and MobsPropertiesRandomness.log  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
E.g. https://pastebin.com/1AbCDEFG

Mob Properties Randomness log (I just copied and pasted it here because its not very long):
[INFO] Reloading Groups 
[INFO] Correctly reloaded all Groups 
[INFO] Reloading Mobs 
[INFO] Mob Randomness.json 
[INFO] Correctly reloaded all Mobs 
[INFO] Reloading Presets 
[INFO] Correctly reloaded all Presets 

(crash log):
[yrCxs0iY.txt](https://github.com/Insane96/MobsPropertiesRandomness/files/7271850/yrCxs0iY.txt)

//Send the mod's config folder with all the jsons and groups
**Config Folder**:  
E.g. MobsPropertiesRandomness.zip

(config folder):
[MobsPropertiesRandomness.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/7271868/MobsPropertiesRandomness.zip)

**Can be reproduced with Mobs Properties Randomness + InsaneLib only?**:  
Yes

**Comment by Insane96** [comment]
Fixed for the next update
