### ISSUE TITLE
Armor percentages doesn't seem to work.

### ISSUE THREAD

**Issue by ChaseRox** [Insane-96/MobRandomness#9]
For example have the chest armor set to the following but the mobs almost always spawn with full armor.	

minecraft:zombie,1.0,minecraft:diamond_chestplate,minecraft:iron_chestplate,minecraft:gold_chestplate,minecraft:leather_chestplate

minecraft:skeleton,1.0,minecraft:diamond_chestplate,minecraft:iron_chestplate,minecraft:gold_chestplate,minecraft:leather_chestplate

**Comment by ChaseRox** [comment]
Also, Is there anyway to disable the server spam of all the mobs spawning with armor?

**Comment by Insane-96** [comment]
Both bugs

**Comment by Insane-96** [comment]
Fixed in Release 1.1.2
