### ISSUE TITLE
1.12.2, Override Vanilla not working?

### ISSUE THREAD

**Issue by ghost** [Insane-96/MobRandomness#92]
Follow the following guideline. Not following this will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

## **Versions**:  MobsPropertiesRandomness-2.3.3-mc1.12.x
* Minecraft:  1.12.2

## **What Happens**:  
`"override_vanilla": true,` does not work for Skeletons in 1.12.2.

According to the [1.12.2 Wiki](https://github.com/Insane96/MobsPropertiesRandomness/wiki/%5B1.12%5D-Equipment#equipment-equipment), "override_vanilla" should work?

Here's what I have:

		"equipment": {
		
		"main_hand": {
		"chance": {
		"amount": 100
            },

            "items": [
                
				{
                    "id": "spartanweaponry:longbow_wood",
                    "override_vanilla":true,
                    "weight": 10,
                    "drop_chance": 10
				}
                
		            ]
		        }

## MobsPropertiesRandomness.log  

[MobsPropertiesRandomness.log](https://github.com/Insane96/MobsPropertiesRandomness/files/7874132/MobsPropertiesRandomness.log)

**Can be reproduced with Mobs Properties Randomness + InsaneLib only?**:  
Yes

**Comment by Insane96** [comment]
The log is corrupted, can't open it.
Also you didn't send the config folder with the scripts.

**Comment by ghost** [comment]
> The log is corrupted, can't open it.

I'm not sure this is a problem from my end? I can open it just fine, from this github page, in multiple different browsers.

Here's my MRP log in pastebin form: https://pastebin.com/Npz9LgZB

Here's my latest skeleton config: https://pastebin.com/vzFiF0ku

If you see the main_hand section, none of the `override_vanilla` key inputs have any result in-game. Is the key spelled differently?

**Comment by Insane96** [comment]
There is no `override_vanilla` in the json you've sent me.

Il Mar 18 Gen 2022, 05:48 roccscout ***@***.***> ha scritto:

**Comment by ghost** [comment]
Ok, here is the latest skeleton.json: https://pastebin.com/2XZtUGG7

Here is the latest log with `override_vanilla`: https://pastebin.com/zhXrcrV4

You will see that the log does output `mainHand: Slot{overrideVanilla: true`, BUT:

In-game, the default minecraft Bow is not overridden.

I encourage you to use your own mod in 1.12.2, and try to replace the default skeleton's bow with any other item or weapon.

MPR can successfully replace the helmet, chest, legs, boots, and offhand of skeletons, but even `override_vanilla` doesn't work on the mainhand default skeleton bow.

**Comment by Insane96** [comment]
This simple script works, so make sure you're using the correct item IDs or that other mods aren't interfering with equipment.
![image](https://user-images.githubusercontent.com/7185104/149884513-cde3b554-110a-4c25-af3a-afc4ef9acd05.png)

Also you replied "Yes" to the question "Can be reproduced with MobsPropertiesRandomness only?" while you're using other mods ...

**Comment by ghost** [comment]
I figured it out! I wasn't crazy afterall, but there is an odd bug (bug?) with the /summon command.

Summoning skeletons with the /summon command will **not ever** summon them with an override_vanilla item. However, naturally spawning skeletons or those spawned with mob spawners will have their original bows overridden.

So my configs were working fine, but /summon will never work to test out whether `override_vanilla` works. You have to see them spawned naturally.

**Comment by Insane96** [comment]
Do spawn eggs work?

**Comment by Insane96** [comment]
No response. Closing

**Comment by ghost** [comment]
> Do spawn eggs work?

Sorry, yes they do work with spawn eggs! Using /summon won't always have the changes from the config present, but spawn eggs and natural spawns do.
