### ISSUE TITLE
.json mob files will not load correctly, even with precise format

### ISSUE THREAD

**Issue by ChrissCross717** [Insane-96/MobRandomness#95]
**Versions**:
* Minecraft:  1.16.5
* Forge: 36.2.29
* Mobs Properties Randomness: 3.2.3
* InsaneLib: 1.4.2

**What Happens**:  
As in the title, the mod simply does not work. Reloading and tuning mob .json files does nothing to fix the "Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $" error. I even copy/pasted an example template from the wiki without tinkering it and still received the same error. I assume the code is looking for a { and couldn't find it, but I could very well be wrong. I have no idea what the issue might be otherwise.

Log below is using template example.
 

**Logs / Crash reports**:  
https://pastebin.com/pxacm6QZ

**Config Folder**:  
[MobsPropertiesRandomnessConfig.zip](https://github.com/Insane96/MobsPropertiesRandomness/files/8322004/MobsPropertiesRandomnessConfig.zip)

**Can be reproduced with Mobs Properties Randomness only? (InsaneLib is mandatory in 1.16+)**:  
Yes

**Comment by Insane96** [comment]
The error is on the .DS_store file, not the zomb.json
